#!/bin/bash

# choose which to progs to try:
inkscape=true
gs=true
imagemagick=true
pdftops=true

conversion (){
  # get file name without extension, full path
  b=`basename -s .pdf $1`

  full=`grealpath $1`
  echo "Converting: $1 (Absolute path: $full)"

  dir="`dirname $full`/converted"
  mkdir -p $dir

  ###  Inkscape
  if [ $inkscape = true ]; then
    inkscape $full --export-eps=${dir}/${b}_inkscape.eps
    if [ $? -ne 0 ]; then echo "Inkscape failed" && inkscape=false; fi
  fi

  ###  ImageMagick
  if [ $imagemagick = true ]; then
    convert $full ${dir}/${b}_imagemagick.eps
    if [ $? -ne 0 ]; then echo "ImageMagick failed" && imagemagick=false; fi
  fi

  ###  ghostscript
  if [ $gs = true ]; then
    gs -q -dNOCACHE -dNOPAUSE -dBATCH -dSAFER -sDEVICE=eps2write -sOutputFile=${dir}/${b}_gs.eps $full
    if [ $? -ne 0 ]; then echo "Ghostscript failed" && gs=false; fi
  fi

  ###  pdftops
  if [ $pdftops = true ]; then
    pdftops -eps $full
    mv "`dirname $full`/$b.eps" ${dir}/${b}_pdftops.eps 2>/dev/null
    if [ $? -ne 0 ]; then echo "pdftops failed" && pdftops=false; fi
  fi
}

if [[ -f $1 ]]; then
  # if a single file
  conversion $1

elif [[ -d $1 ]]; then
  # else if a directory
  for i in `ls $1/*.pdf`; do
    conversion $i
  done

else
  echo "Call: ./pdf2eps [PDF file]"
  exit 1
fi
